services:
  - type: web
    name: hr-platform-api
    env: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: starter
    branch: main
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: postgres
          property: port
      - key: DB_USER
        fromDatabase:
          name: postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: postgres
          property: password
      - key: DB_NAME
        fromDatabase:
          name: postgres
          property: database
      - key: REDIS_HOST
        fromService:
          type: redis
          name: redis
          property: host
      - key: REDIS_PORT
        value: 6379
      - key: RABBITMQ_URL
        fromService:
          type: pserv
          name: rabbitmq
          property: url
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false

  - type: redis
    name: redis
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: noeviction

  - type: pserv
    name: rabbitmq
    env: docker
    repo: https://github.com/rabbitmq/rabbitmq-server.git
    dockerfilePath: ./Dockerfile
    plan: starter
    disk:
      name: data
      mountPath: /var/lib/rabbitmq
      sizeGB: 1

databases:
  - name: postgres
    databaseName: hr_platform
    plan: starter