export enum ProgrammingLanguage {
  JAVASCRIPT = 'javascript',
  TYPESCRIPT = 'typescript',
  PYTHON = 'python',
  JAVA = 'java',
  CSHARP = 'c#',
  CPP = 'c++',
  PHP = 'php',
  RUBY = 'ruby',
  SWIFT = 'swift',
  KOTLIN = 'kotlin',
  GO = 'go',
  RUST = 'rust',
  HTML = 'html',
  CSS = 'css',
  SQL = 'sql',
  MONGODB = 'mongodb',
  REACT = 'react',
  ANGULAR = 'angular',
  VUE = 'vue',
  NODEJS = 'nodejs',
  DOCKER = 'docker',
  KUBERNETES = 'kubernetes',
  AWS = 'aws',
  AZURE = 'azure',
  GCP = 'gcp',
}
